version: '3.1'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 28080:8080

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pjbFEUj24X3
      MYSQL_DATABASE: AI
      MYSQL_USER: AI
      MYSQL_PASSWORD: de7xGdeKNkH
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
    volumes:
      - db-storage:/var/lib/mysql

  PacketAnalyze:
    image: openjdk:11.0.8-jre
    restart: always
    network_mode: "host"
    tty: true
    volumes:
      - ./Packet_analyze/CICFlowMeter.jar:/CICFlowMeter.jar
      - ./Packet_analyze/libjnetpcap.so:/usr/local/openjdk-11/lib/libjnetpcap.so
      - ./Packet_analyze/libpcap.so.1.9.1:/usr/local/openjdk-11/lib/libpcap.so.0.8
    environment:
      - "ES_IP=localhost"
      - "ES_PORT=19200"
      - "ES_INDEX_PREFIX=cic_"
      - "READ_LOCAL_FILE=FALSE"
      - "NETWORK_INTERFACE=$IF_NAME"
      - "WRITE_TO_CSV=FALSE"
    command: "java -jar /CICFlowMeter.jar"

  OMP:
    image: csti/omp:v1
    build:
      context: "./OMP/"
      dockerfile: "Dockerfile"
    restart: always
    volumes:
    - "./OMP/code/:/usr/src/omp/code/"
    - "./OMP/data/:/usr/src/omp/code/data/"



volumes:
  db-storage:
    driver: local


# TODO: container 要連到 ES