version: '3.1'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 28080:8080

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pjbFEUj24X3
      MYSQL_DATABASE: AI
      MYSQL_USER: AI
      MYSQL_PASSWORD: de7xGdeKNkH
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
    volumes:
      - db-storage:/var/lib/mysql

  PacketAnalyze:
    image: openjdk:11-jdk-alpine
    restart: always
    network_mode: "host"
    volumes:
      - ./PacketAnalyze/CICFlowMeter.jar:/CICFlowMeter.jar
      - ./PacketAnalyze/libjnetpcap.so:/opt/openjdk-16/lib/libjnetpcap.so
    command: "java -jar /CICFlowMeter.jar"

  OMP:
    image: csti/omp:v1
    build:
      context: "./OMP/"
      dockerfile: "Dockerfile"
    restart: always
    volumes:
    - "./OMP/code/:/usr/src/omp/code/"
    - "./OMP/data/:/usr/src/omp/code/data/"



volumes:
  db-storage:
    driver: local


# TODO: container 要連到 ES